export const filterMonospaceWhitelist = [
  'Job Status',
  'System',
  'CommPk',
  'CommPkg',
  'Comm Pkg',
  'Location',
  'Material Status',
  'Material status',
  'Project',
  'Area',
  'Mc Package Phase',
  'Subsystem',
  'Remark',
  'Form Type',
  'Commissioning Priority 1',
  'Priority',
  'Switchboard',
  'Circuit',
];
