name: Generate Github Docs

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'vue-press/**'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Check out
              uses: actions/checkout@v2.3.1
              with:
                  ref: main

            - name: Generate Docs
              run: |
                  npm install
                  npm run build
            - name: Deploy Docs
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: docs
                  folder: docs
