name: Verify linked issue

# This action works with pull requests and pushes
permissions:
  {
    contents: write,
    actions: write,
    checks: write,
    deployments: write,
    discussions: write,
    id-token: write,
    issues: write,
    packages: write,
    pages: write,
    pull-requests: write,
    repository-projects: write,
    security-events: write,
    statuses: write,
  }
on:
  pull_request:

jobs:
  issue-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - run: npm run first-time-setup

      - run: pnpm tsx ./.github/helpers/src/issue-checker.ts issue -T ${{ github.token }} -P ${{github.event.number}}
