name: 👮Verify linked issue

# This action works with pull requests and pushes
permissions:
  {
    contents: read,
    actions: read,
    checks: read,
    deployments: read,
    discussions: read,
    id-token: write,
    issues: write,
    packages: read,
    pages: read,
    pull-requests: write,
    repository-projects: read,
    security-events: read,
    statuses: read,
  }
on:
  pull_request:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/pr-check-issues.yml
    with:
      pr: ${{github.event.number}}
