name: Publish changed
on:
  push:
    branches:
      - main
      - preview/server-side
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm
    env:
      NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm run first-time-setup
      #... previous steps
      # Run `build` script in every projects
      - run: pnpm run build
      # Set token
      - run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      # Publish all packages in the workspace which version still does not exist
      - run: pnpm shipit --no-git-checks
