name: Publish changed
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm
    env:
      NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: PNPM setup
        uses: ./.github/actions/pnpm-setup

      - name: Build monorepo
        run: pnpm build

      - name: Publish NPM
        run: |
          pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          pnpm shipit --no-git-checks
