name: Release

on:
    push:
        branches:
            - main
        paths:
            - 'packages/**'

jobs:
    release-pkg:
        name: Create release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
                  path: main
            - uses: pnpm/action-setup@v2
              with:
                  version: 7.14.0
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: pnpm install -r --frozen-lockfile
            - run: pnpm run -r build
            - name: Bump versions
              run: npx lerna version --yes --create-release github
              env:
                  GH_TOKEN: ${{ github.token }}

            - name: Release packages
              run: pnpm -r publish --no-git-checks --access public
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
