name: Release

on:
    push:
        branches:
            - main
        paths:
            - 'packages/**'

jobs:
    release-pkg:
        name: Create release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: pnpm/action-setup@v2
              with:
                  version: 7.14.0
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: pnpm install -r --frozen-lockfile
            - run: pnpm run -r build
            - name: Config git user
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git fetch --depth=1 origin +refs/tags/*:refs/tags/*
            - name: Bump versions
              run: npx lerna version --yes --create-release github
              env:
                  GH_TOKEN: ${{ github.token }}

            - name: Release packages
              run: pnpm -r publish --no-git-checks --access public
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
